//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка_()
        {
            this.Комментарии_ = new HashSet<Комментарии_>();
        }
    
        public int Номер { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<int> Код_оргтехники { get; set; }
        public Nullable<int> Код_модели { get; set; }
        public Nullable<int> Код_проблемы { get; set; }
        public Nullable<int> Код_статуса_заявки { get; set; }
        public Nullable<System.DateTime> Дата_конца { get; set; }
        public Nullable<int> Код_запчасти { get; set; }
        public Nullable<int> Код_мастера { get; set; }
        public Nullable<int> Код_клиента { get; set; }
    
        public virtual Запчасти_ Запчасти_ { get; set; }
        public virtual Модели_ Модели_ { get; set; }
        public virtual Оргтехника_ Оргтехника_ { get; set; }
        public virtual Пользователи_ Пользователи_ { get; set; }
        public virtual Пользователи_ Пользователи_1 { get; set; }
        public virtual Проблемы Проблемы { get; set; }
        public virtual C_Статус_заявки__ C_Статус_заявки__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Комментарии_> Комментарии_ { get; set; }
    }
}
