//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комментарии_
    {
        public int Код { get; set; }
        public string Сообщение { get; set; }
        public Nullable<int> Код_мастера { get; set; }
        public Nullable<int> Код_заявки { get; set; }
    
        public virtual Заявка_ Заявка_ { get; set; }
        public virtual Пользователи_ Пользователи_ { get; set; }
    }
}
